// <auto-generated />
using EquiposDemoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquiposDemoApi.Migrations
{
    [DbContext(typeof(EquiposDbContext))]
    [Migration("20230816170437_AgregarDatosCategorias")]
    partial class AgregarDatosCategorias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("EquiposDemoApi.Modelos.CategoriaEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoriasEquipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreCategoria = "Electrodomesticos"
                        },
                        new
                        {
                            Id = 2,
                            NombreCategoria = "Construccion"
                        },
                        new
                        {
                            Id = 3,
                            NombreCategoria = "Utiles Medicos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
